### ISSUE TITLE
Keystore and Tag error

### ISSUE THREAD

**Issue by 98h398hrpohpoai** [TheBlusky/ntfy-android-builder#1]
Hey, thanks for putting this together! I tried running this on debian bookworm with docker 24.0.7 and ran into the following:

```
Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
        for: CN=ntfy, OU=ntfy, O=ntfy, L=ntfy, ST=ntfy, C=nt
[Storing /volumes/keystore/keystore.jks]
keytool error: java.io.FileNotFoundException: /volumes/keystore/keystore.jks (Permission denied)
java.io.FileNotFoundException: /volumes/keystore/keystore.jks (Permission denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
        at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1375)
        at java.base/sun.security.tools.keytool.Main.run(Main.java:423)
        at java.base/sun.security.tools.keytool.Main.main(Main.java:416)
```

I didn't modify anything related keystore or see anything in the readme. Following that, ran into

```
Cloning into 'ntfy-android'...
remote: Enumerating objects: 11125, done.
remote: Counting objects: 100% (11125/11125), done.
remote: Compressing objects: 100% (2697/2697), done.
remote: Total 11125 (delta 6408), reused 10989 (delta 6379), pack-reused 0
Receiving objects: 100% (11125/11125), 53.16 MiB | 18.90 MiB/s, done.
Resolving deltas: 100% (6408/6408), done.
error: pathspec 'v2.8.0' did not match any file(s) known to git
```
Which then failed. v2.8.0 is the current version of ntfy and seems as though it should succeed unless I've missed something.

**Comment by 98h398hrpohpoai** [comment]
It's late and I made a dumb-dumb in mistaking ntfy version for ntfy-android version.

Given the .env variable is labeled ntfy_tag, perhaps considering renaming to ntfy_android_tag for improved clarity?

Build now produces the following failure

```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :app:buildKotlinToolingMetadata
> Task :app:preBuild UP-TO-DATE
> Task :app:prePlayReleaseBuild UP-TO-DATE
> Task :app:compilePlayReleaseAidl NO-SOURCE
> Task :app:compilePlayReleaseRenderscript NO-SOURCE
> Task :app:generatePlayReleaseBuildConfig
> Task :app:generatePlayReleaseResValues
> Task :app:generatePlayReleaseResources
> Task :app:processPlayReleaseGoogleServices FAILED
> Task :app:checkPlayReleaseAarMetadata

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processPlayReleaseGoogleServices'.
> No matching client found for package name 'io.heckel.ntfy'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 7s
5 actionable tasks: 5 executed
```

**Comment by TheBlusky** [comment]
Nice to hear someone is interested in this project :-)

Your first error might be because your volume is owned by root. Try changing directory permissions of volume you can try `chmod -R 777 ./volumes/keystore` (from project directory) on your host, so when docker tries to create the keystore, it should be authorized.

For your second error, I'll try to check it later on my device. Maybe I'll need to fix the script.

**Comment by TheBlusky** [comment]
Oh, good catch for ntfy version.

So no update in ntfy android version since I built this. It should work fine.

Have you managed to fix the keystore creation issue ?

**Comment by 98h398hrpohpoai** [comment]
I did. You were right about the perms. Used chmod -R 0777 to test and it cleared up the keystore issue.
Still run into the "No matching client found for package name 'io.heckel.ntfy'" build error though.

**Comment by 98h398hrpohpoai** [comment]
So it looks like this was user-error through-and-through. 
When I configured the app in the firebase console, I used a different package name.
Reconfiguring the package name to "io.heckel.ntfy"in google-service.json allows the build to complete.

Edit: Installed and working perfectly. Thanks for taking the time to put this together--it's a wicked convenient tool!
